<footer class="small">
    <div class="row">
        <div class="col-md-6">
            <a href="" class="">Política de Privacidade</a>                        
            <a href="" class="">Termo de Uso</a>                        
        </div>
        <div class="col-md-6 text-right">
            <?php echo $this->translate("Todos os direitos reservados"); ?>
        </div>                    
    </div>
</footer>